name: How Fast can I go?
favicon: null
layout_spectrum: 0.50059
typography_spectrum: 0.5536425274331123
title: 'Running Experiment '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6a6c6b'
    - '#050608'
    - '#c2c6c9'
    - '#553924'
    - '#c3aa10'
  brandStrength: 0.3125
  lightness: 0.4273489424958825
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
